/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Admin;

import Controlador.CtlPregunta;
import Controlador.CtlTema;
import Controlador.Main;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Daryl Ospina
 */
public class pnlPregUsus extends javax.swing.JPanel {

    private final int modificador;
    private CtlPregunta controladorPreg;
    private CtlTema controladorTema;

    /**
     * Creates new form pnlPreguntas
     *
     * @param modificador
     */
    public pnlPregUsus(int modificador) {
        initComponents();
        this.modificador = modificador;
        switch (modificador) {
            case 0:
                tbl.setModel(Main.controUsuario.listar());
                break;
            case 1:
                controladorPreg = new CtlPregunta();
//            tbl.setModel(controladorPreg.listar());
                break;
            case 2:
                controladorTema = new CtlTema();
                tbl.setModel(controladorTema.listar());
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnUsuarios = new javax.swing.JButton();
        btnUsuarios1 = new javax.swing.JButton();
        btnUsuarios2 = new javax.swing.JButton();
        btnUsuarios3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 134, 150));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        btnUsuarios.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/add.png"))); // NOI18N
        btnUsuarios.setText("CREAR");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnUsuarios1.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios1.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/modify.png"))); // NOI18N
        btnUsuarios1.setText("MODIFICAR");
        btnUsuarios1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios1ActionPerformed(evt);
            }
        });

        btnUsuarios2.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios2.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/remove.png"))); // NOI18N
        btnUsuarios2.setText("ELIMINAR");
        btnUsuarios2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios2ActionPerformed(evt);
            }
        });

        btnUsuarios3.setBackground(new java.awt.Color(75, 117, 137));
        btnUsuarios3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUsuarios3.setForeground(new java.awt.Color(0, 0, 29));
        btnUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/update.png"))); // NOI18N
        btnUsuarios3.setText("ACTUALIZAR TABLA");
        btnUsuarios3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        btnUsuarios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        JDialog ventana;
        switch (modificador) {
            case 0:
                ventana = new FrmPregUsu(null, true, 0, this);
                break;
            case 1:
                ventana = new FrmPregUsu(null, true, 1, this);
                break;
            case 2:
                ventana = new FrmTema(null, true);
                tbl.setModel(controladorTema.listar());
                break;
            default:
                return;
        }
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios1ActionPerformed
        // TODO add your handling code here:
        JDialog ventana;
        if (tbl.getSelectedRow() == -1) {
            switch (modificador) {
                case 0:
                    String cedula = JOptionPane.showInputDialog("Ingrese La Cedula Del Usuario Que Desea Modificar");
                    if (cedula != null) {
                        ventana = new FrmPregUsu(Main.controUsuario.traerUsuario(Integer.parseInt(cedula)), null, true, 0, this);
                    } else {
                        return;
                    }
                    break;
                case 1:
                    ventana = new FrmPregUsu(null, true, 1, this);
                    break;
                case 2:
                    String idTema = JOptionPane.showInputDialog("Ingrese el numero del tema que desea modificar");
                    if (idTema != null) {
                        ventana = new FrmTema(null, true);
                        tbl.setModel(controladorTema.listar());
                    }else{
                        return;
                    }
                    break;
                default:
                    return;
            }
        } else {
            if (modificador == 0) {
                ventana = new FrmPregUsu(Main.controUsuario.traerUsuario((int) tbl.getValueAt(tbl.getSelectedRow(), 0)), null, true, 0, this);
            } else {
                ventana = new FrmPregUsu(null, true, 1, this);
            }
        }
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuarios1ActionPerformed

    private void btnUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios2ActionPerformed
        // TODO add your handling code here:
        if (tbl.getSelectedRow() == -1) {
            if (modificador == 0) {
                String cedula = JOptionPane.showInputDialog("Ingrese La Cedula Del Usuario Que Desea Modificar");
                Main.controUsuario.solicitarEliminar(cedula);
                tbl.setModel(Main.controUsuario.listar());
            } else {

            }
        } else {
            if (modificador == 0) {
                String cedula = tbl.getValueAt(tbl.getSelectedRow(), 0) + "";
                int desicion = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar el usuario con la cedula: " + cedula);
                if (desicion == 0) {
                    Main.controUsuario.solicitarEliminar(cedula);
                    tbl.setModel(Main.controUsuario.listar());
                }
            } else {

            }
        }
    }//GEN-LAST:event_btnUsuarios2ActionPerformed

    private void btnUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios3ActionPerformed
        // TODO add your handling code here:
        if (modificador == 0) {
            tbl.setModel(Main.controUsuario.listar());
        } else {
            controladorPreg = new CtlPregunta();
//            tbl.setModel(controladorPreg.listar());
        }
    }//GEN-LAST:event_btnUsuarios3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnUsuarios1;
    private javax.swing.JButton btnUsuarios2;
    private javax.swing.JButton btnUsuarios3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    public void listar() {
        if (modificador == 0) {
            tbl.setModel(Main.controUsuario.listar());
        } else {
            controladorPreg = new CtlPregunta();
//            tbl.setModel(controladorPreg.listar());
        }
    }
}
